version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile

    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: explain_training
      MYSQL_USER: mrrobot
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d